spring.application.name=campusbazaar

spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres?user=postgres.pfdnafifakvfckjwctoz&password=CampusBazaarR123&prepareThreshold=0
spring.datasource.username=postgres.pfdnafifakvfckjwctoz
spring.datasource.password=CampusBazaarR123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=20000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

app.jwt.secret=campusbazaar-super-secret-jwt-key-it342-lao-2024-minimum-256-bits
app.jwt.expiration=86400000

spring.web.resources.static-locations=file:uploads/,classpath:/static/
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=367885242421-2foj8m7u55216989hsj91ls7oemejtqm.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile

# Frontend URL
app.frontend.url=http://localhost:5173