spring.application.name=campusbazaar

spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres?user=postgres.pfdnafifakvfckjwctoz&password=CampusBazaarR123
spring.datasource.username=postgres.pfdnafifakvfckjwctoz
spring.datasource.password=CampusBazaarR123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

app.jwt.secret=campusbazaar-super-secret-jwt-key-it342-lao-2024-minimum-256-bits
app.jwt.expiration=86400000